# Generated by Django 5.0.2 on 2024-02-14 23:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='published',
            field=models.IntegerField(help_text='Use the format: YYYY', validators=[django.core.validators.MinValueValidator(1800), django.core.validators.MaxValueValidator(2024)]),
        ),
    ]
